### ISSUE TITLE
add section about MIT licensing

### ISSUE THREAD

**Issue by kathryn-willi** [rossyndicate/ROSSyndicate_best_practices#23]
(Unless it's already in there - but neither Caitlin nor I can find it if it is. o_O)

**Comment by kathryn-willi** [comment]
@steeleb didn't you add this into the best practices? if so I am going to close this one!

**Comment by steeleb** [comment]
Yup!! It's in section 3.1. No idea when that was updated. :) Thanks for cleaning up our issues.
